<a href="https://colab.research.google.com/github/Akbar-AI97/ai_foundation/blob/main/pandas_MIT36.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

--------- SHOURTCUTS ------------
1. shift + enter => open a new cell
2. cmd + enter => run current cell
3. shift + cmd + enter => run a specific line
4. cmd + / => comment the current line
5. shift + # => comment after the code in the current line
6. cmd + M + D => delete current cell

In [2]:
# pip install pandas

In [4]:
import pandas as pd

In [9]:
# pandas version check
print(pd.__version__)

2.2.2

In [13]:
# DataFrame() - forms a tabular data

mydataset = {
    'cars': ["BMW", "Volvo", "Ford", "Tesla", "Ferrari", "Ford", "BMW"],
    'counts': [3, 7, 2, 8, 1, 9, 3]
}

df = pd.DataFrame(mydataset)
print(df)

      cars  counts
0      BMW       3
1    Volvo       7
2     Ford       2
3    Tesla       8
4  Ferrari       1
5     Ford       9
6      BMW       3

 ------------- METHODS --------------

In [18]:
# head() - first 5 rows by default
df.head()

      cars  counts
0      BMW       3
1    Volvo       7
2     Ford       2
3    Tesla       8
4  Ferrari       1

In [22]:
# tail() - last 5 rows by default
df.tail()

      cars  counts
2     Ford       2
3    Tesla       8
4  Ferrari       1
5     Ford       9
6      BMW       3

In [26]:
# shape

df.shape

(7, 2)

In [29]:
# columns

df.columns

Index(['cars', 'counts'], dtype='object')

In [38]:
# dtypes

df.dtypes

cars      object
counts     int64
dtype: object

In [39]:
print(df)

      cars  counts
0      BMW       3
1    Volvo       7
2     Ford       2
3    Tesla       8
4  Ferrari       1
5     Ford       9
6      BMW       3

In [40]:
# describe() - numerical columns only

df.describe()

# count -> Number of non-missing (non-NaN) values
# mean  -> Average value of the column
# std   -> Standard deviation (how spread out the values are)
# min   -> Smallest value in the column
# 25%   -> First quartile (25% of values are below this)
# 50%   -> Median (middle value, 50th percentile)
# 75%   -> Third quartile (75% of values are below this)
# max   -> Largest value in the column

         counts
count  7.000000
mean   4.714286
std    3.199702
min    1.000000
25%    2.500000
50%    3.000000
75%    7.500000
max    9.000000

In [42]:
df.describe(include="all")

       cars    counts
count     7  7.000000
unique    5       NaN
top     BMW       NaN
freq      2       NaN
mean    NaN  4.714286
std     NaN  3.199702
min     NaN  1.000000
25%     NaN  2.500000
50%     NaN  3.000000
75%     NaN  7.500000
max     NaN  9.000000

In [49]:
# iloc - selects a specific row

df.iloc[0]

cars      BMW
counts      3
Name: 0, dtype: object

In [51]:
df.iloc[1:4] # [1, 4)

    cars  counts
1  Volvo       7
2   Ford       2
3  Tesla       8

In [53]:
df.iloc[2:] # [2, end]

      cars  counts
2     Ford       2
3    Tesla       8
4  Ferrari       1
5     Ford       9
6      BMW       3

In [60]:
# loc[row, "column_name"]

df.loc[2:5, "cars"]

2       Ford
3      Tesla
4    Ferrari
5       Ford
Name: cars, dtype: object

In [62]:
# Conditional Selection / Filtering

df["counts"] > 3

0    False
1     True
2    False
3     True
4    False
5     True
6    False
Name: counts, dtype: bool

In [64]:
print(df)

      cars  counts
0      BMW       3
1    Volvo       7
2     Ford       2
3    Tesla       8
4  Ferrari       1
5     Ford       9
6      BMW       3

In [68]:
df[df["counts"] <= 3]

      cars  counts
0      BMW       3
2     Ford       2
4  Ferrari       1
6      BMW       3

In [72]:
df[df["cars"] == "BMW"]

  cars  counts
0  BMW       3
6  BMW       3

In [75]:
# df.mean(numeric_only=True)
df["counts"].mean()

np.float64(4.714285714285714)

In [77]:
df.sum()

cars      BMWVolvoFordTeslaFerrariFordBMW
counts                                 33
dtype: object

In [80]:
df.min()

cars      BMW
counts      1
dtype: object

In [82]:
df.max()

cars      Volvo
counts        9
dtype: object

In [84]:
df.median(numeric_only=True)

counts    3.0
dtype: float64

In [87]:
df.count() # Returns non null values only

cars      7
counts    7
dtype: int64

In [89]:
df.std(numeric_only=True)

counts    3.199702
dtype: float64

---------- CLEANING MISSING DATA ------------

In [91]:
# creating a dataset with missing data

data_with_missing = {
    "cars": ["BMW", "Volvo", None, "Tesla", "Ferrari", None, "BMW"],
    "counts": [3, 7, None, 8, 1, 9, None]
}

df_missing = pd.DataFrame(data_with_missing)
print(df_missing)

      cars  counts
0      BMW     3.0
1    Volvo     7.0
2     None     NaN
3    Tesla     8.0
4  Ferrari     1.0
5     None     9.0
6      BMW     NaN

In [95]:
# counting missing data

df_missing.isnull().sum()

cars      2
counts    2
dtype: int64

In [110]:
# dropna() - deleting missing data

df_missing.dropna()
df_missing.dropna(how="all")  # checks by rows with all null data
df_missing.dropna(axis=1)     # checks by column
df_missing.dropna(subset=["counts"]) # checks by subsets

      cars  counts
0      BMW     3.0
1    Volvo     7.0
3    Tesla     8.0
4  Ferrari     1.0
5     None     9.0

In [115]:
# fillna() - filling missing data

df_missing.fillna("unknown")
df_missing.fillna(0)

df_missing.fillna({"cars": "unknown", "counts": 0})

      cars  counts
0      BMW     3.0
1    Volvo     7.0
2  unknown     0.0
3    Tesla     8.0
4  Ferrari     1.0
5  unknown     9.0
6      BMW     0.0

---------- READING DATASETS ----------

* scv file -> df = pd.read_csv("file_name.csv")
* exel file -> df = pd.read_excel("file_name.xlsx")
* json file -> df = pd.read_json("file_name.json")

In [120]:
df = pd.read_csv("Titanic-Dataset.csv")

df.head(30)

# df = pd.read_excel("file_name.xlsx")
# df = pd.read_json("file_name.json")

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
12,13,0,3,"Saundercock, Mr. William Henry",male,20.0,0,0,A/5. 2151,8.0500,NaN,S
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.2750,NaN,S
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0,0,350406,7.8542,NaN,S
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000,NaN,S
16,17,0,3,"Rice, Master. Eugene",male,2.0,4,1,382652,29.1250,NaN,Q
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S
18,19,0,3,"Vander Planke, Mrs. Julius (Emelia Maria Vande...",female,31.0,1,0,345763,18.0000,NaN,S
19,20,1,3,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,7.2250,NaN,C
20,21,0,2,"Fynney, Mr. Joseph J",male,35.0,0,0,239865,26.0000,NaN,S
21,22,1,2,"Beesley, Mr. Lawrence",male,34.0,0,0,248698,13.0000,D56,S
22,23,1,3,"McGowan, Miss. Anna ""Annie""",female,15.0,0,0,330923,8.0292,NaN,Q
23,24,1,1,"Sloper, Mr. William Thompson",male,28.0,0,0,113788,35.5000,A6,S
24,25,0,3,"Palsson, Miss. Torborg Danira",female,8.0,3,1,349909,21.0750,NaN,S
25,26,1,3,"Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...",female,38.0,1,5,347077,31.3875,NaN,S
26,27,0,3,"Emir, Mr. Farred Chehab",male,NaN,0,0,2631,7.2250,NaN,C
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.0,3,2,19950,263.0000,C23 C25 C27,S
28,29,1,3,"O'Dwyer, Miss. Ellen ""Nellie""",female,NaN,0,0,330959,7.8792,NaN,Q
29,30,0,3,"Todoroff, Mr. Lalio",male,NaN,0,0,349216,7.8958,NaN,S

---------- SAVING DATASETS ----------

* to exel file -> df.to_excel("file_name.xlsx")

In [122]:
df.to_excel("output.xlsx")

In [124]:
# Series => 1D arrays

cars = pd.Series(["BMW", "Volvo", "Ford", "Tesla", "Ferrari", "Ford", "BMW"])
print(cars)

0        BMW
1      Volvo
2       Ford
3      Tesla
4    Ferrari
5       Ford
6        BMW
dtype: object

In [126]:
cars_series = data_with_missing['cars']
print(cars_series)

['BMW', 'Volvo', None, 'Tesla', 'Ferrari', None, 'BMW']